### PR TITLE
makes the display a little prettier

### PR DESCRIPTION
**Pull request by ablwr**

### CODE REVIEW

**Comment by dericed** [comment]
With this command: `mediaconch -p movtricks_policies.xml -d oneline.xsl *.mov`

Before:
```
pass,1a_int_tff.mov,"Is the file consistent and clear?"fail,1b_int_tff-container_unk-encoding.mov,"(Is the file consistent and clear?:[fail:Is ScanType consistent?])"fail,1c_int_bff-encoding_tff-container.mov,"(Is the file consistent and clear?:[fail:Is ScanOrder consistent?])"pass,1c_temp.mov,"Is the file consistent and clear?"fail,1d_unclear_interlacement.mov,"(Is the file consistent and clear?:"(If QuickTime, then are interlacement and aspect ratio clear.:[fail:Not QuickTime?]"(QuickTime with default matrix and fiel and pasp atoms?:[fail:fiel atom is used?])")")"pass,2a_dar.mov,"Is the file consistent and clear?"fail,2b_dar_encoding-container-mismatch.mov,"(Is the file consistent and clear?:[fail:Is ScanType consistent?][fail:Is ScanOrder consistent?][fail:Is DisplayAspectRatio consistent?][fail:Is the Color Description consistent?])"fail,2b_temp.mov,"(Is the file consistent and clear?:[fail:Is ScanType consistent?][fail:Is ScanOrder consistent?])"
fail,2c_unclear_aspect_ratio.mov,"(Is the file consistent and clear?:"(If QuickTime, then are interlacement and aspect ratio clear.:[fail:Not QuickTime?]"(QuickTime with default matrix and fiel and pasp atoms?:[fail:pasp atom is used?])")")"pass,3a_small_frame_size.mov,"Is the file consistent and clear?"fail,3b_size_matrix_scaling.mov,"(Is the file consistent and clear?:"(If QuickTime, then are interlacement and aspect ratio clear.:[fail:Not QuickTime?]"(QuickTime with default matrix and fiel and pasp atoms?:"(Track Header Matrix structure uses defaults:[fail:width scale is 1?][fail:height scale is 0?])")")")"pass,4a_color-encoding-and-container.mov,"Is the file consistent and clear?"fail,4b_color-conflict-encoding-and-container.mov,"(Is the file consistent and clear?:"(Is the Color Description consistent?:[fail:Is colour_primaries_Original present?][fail:Is transfer_characteristics_Original present?][fail:Is matrix_coefficients_Original present?])")"pass,4b_temp.mov,"Is the file consistent and clear?"pass,5a_duration.mov,"Is the file consistent and clear?"fail,5b_duration_change.mov,"(Is the file consistent and clear?:[fail:Is Duration consistent?][fail:Is StreamSize consistent?])"
```
^^^ oops, there needs to be a line break after each file

With line break added:
```
pass,1a_int_tff.mov,"Is the file consistent and clear?"
fail,1b_int_tff-container_unk-encoding.mov,"(Is the file consistent and clear?:[fail:Is ScanType consistent?])"
fail,1c_int_bff-encoding_tff-container.mov,"(Is the file consistent and clear?:[fail:Is ScanOrder consistent?])"
pass,1c_temp.mov,"Is the file consistent and clear?"
fail,1d_unclear_interlacement.mov,"(Is the file consistent and clear?:"(If QuickTime, then are interlacement and aspect ratio clear.:[fail:Not QuickTime?]"(QuickTime with default matrix and fiel and pasp atoms?:[fail:fiel atom is used?])")")"
pass,2a_dar.mov,"Is the file consistent and clear?"
fail,2b_dar_encoding-container-mismatch.mov,"(Is the file consistent and clear?:[fail:Is ScanType consistent?][fail:Is ScanOrder consistent?][fail:Is DisplayAspectRatio consistent?][fail:Is the Color Description consistent?])"
fail,2b_temp.mov,"(Is the file consistent and clear?:[fail:Is ScanType consistent?][fail:Is ScanOrder consistent?])"fail,2c_unclear_aspect_ratio.mov,"(Is the file consistent and clear?:"(If QuickTime, then are interlacement and aspect ratio clear.:[fail:Not QuickTime?]"(QuickTime with default matrix and fiel and pasp atoms?:[fail:pasp atom is used?])")")"
pass,3a_small_frame_size.mov,"Is the file consistent and clear?"
fail,3b_size_matrix_scaling.mov,"(Is the file consistent and clear?:"(If QuickTime, then are interlacement and aspect ratio clear.:[fail:Not QuickTime?]"(QuickTime with default matrix and fiel and pasp atoms?:"(Track Header Matrix structure uses defaults:[fail:width scale is 1?][fail:height scale is 0?])")")")"
pass,4a_color-encoding-and-container.mov,"Is the file consistent and clear?"
fail,4b_color-conflict-encoding-and-container.mov,"(Is the file consistent and clear?:"(Is the Color Description consistent?:[fail:Is colour_primaries_Original present?][fail:Is transfer_characteristics_Original present?][fail:Is matrix_coefficients_Original present?])")"
pass,4b_temp.mov,"Is the file consistent and clear?"
pass,5a_duration.mov,"Is the file consistent and clear?"
fail,5b_duration_change.mov,"(Is the file consistent and clear?:[fail:Is Duration consistent?][fail:Is StreamSize consistent?])"
```

After:
```
pass! 1a_int_tff.mov | Is the file consistent and clear? fail! 1b_int_tff-container_unk-encoding.mov | Is the file consistent and clear? 
  --  [fail:Is ScanType consistent?]fail! 1c_int_bff-encoding_tff-container.mov | Is the file consistent and clear? 
  --  [fail:Is ScanOrder consistent?]pass! 1c_temp.mov | Is the file consistent and clear? fail! 1d_unclear_interlacement.mov | Is the file consistent and clear?  If QuickTime, then are interlacement and aspect ratio clear. 
  --  [fail:Not QuickTime?] QuickTime with default matrix and fiel and pasp atoms? 
  --  [fail:fiel atom is used?]pass! 2a_dar.mov | Is the file consistent and clear? fail! 2b_dar_encoding-container-mismatch.mov | Is the file consistent and clear? 
  --  [fail:Is ScanType consistent?]
  --  [fail:Is ScanOrder consistent?]
  --  [fail:Is DisplayAspectRatio consistent?]
  --  [fail:Is the Color Description consistent?]fail! 2b_temp.mov | Is the file consistent and clear? 
  --  [fail:Is ScanType consistent?]
  --  [fail:Is ScanOrder consistent?]fail! 2c_unclear_aspect_ratio.mov | Is the file consistent and clear?  If QuickTime, then are interlacement and aspect ratio clear. 
  --  [fail:Not QuickTime?] QuickTime with default matrix and fiel and pasp atoms? 
  --  [fail:pasp atom is used?]pass! 3a_small_frame_size.mov | Is the file consistent and clear? fail! 3b_size_matrix_scaling.mov | Is the file consistent and clear?  If QuickTime, then are interlacement and aspect ratio clear. 
  --  [fail:Not QuickTime?] QuickTime with default matrix and fiel and pasp atoms?  Track Header Matrix structure uses defaults 
  --  [fail:width scale is 1?]
  --  [fail:height scale is 0?]pass! 4a_color-encoding-and-container.mov | Is the file consistent and clear? fail! 4b_color-conflict-encoding-and-container.mov | Is the file consistent and clear?  Is the Color Description consistent? 
  --  [fail:Is colour_primaries_Original present?]
  --  [fail:Is transfer_characteristics_Original present?]
  --  [fail:Is matrix_coefficients_Original present?]pass! 4b_temp.mov | Is the file consistent and clear? pass! 5a_duration.mov | Is the file consistent and clear? fail! 5b_duration_change.mov | Is the file consistent and clear? 
  --  [fail:Is Duration consistent?]
  --  [fail:Is StreamSize consistent?]
```

This one ^ is prettier, but still needs a line break after the last rule. Also if we use this we should probably change the name from `oneline.xsl` to something more accurate. cc'ing @EddyColloton since he's been in needs of concise MediaConch displays.

**Comment by ablwr** [comment]
MORE BREAKS!!! Won't get to update this until after work today, but it's an easy fix.

**Comment by ablwr** [comment]
My data was coming through clean, but I am just working with some randomly-generated and simple .mov files, so my output looks like...

```
fail! mov/test.mov | Is the file consistent and clear?  If QuickTime, then are interlacement and aspect ratio clear.
  --  [fail:Not QuickTime?] QuickTime with default matrix and fiel and pasp atoms?
  --  [fail:fiel atom is used?]fail! mov/test2.mov | Is the file consistent and clear?  If QuickTime, then are interlacement and aspect ratio clear.
  --  [fail:Not QuickTime?] QuickTime with default matrix and fiel and pasp atoms?
  --  [fail:fiel atom is used?]
```

Are the sample files big? You should check them in!

**Comment by retokromer** [comment]
:+1: for changing the name from `oneline.xsl` to something more accurate.

**Pull request merged**
